{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "65675adf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🌿 AtlasLeaf - Sistema de Detecção de Doenças em Soja\n",
      "============================================================\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "AtlasLeaf - Treinamento com SoyNet Dataset\n",
    "Dataset real de campos agrícolas indianos com 9000+ imagens\n",
    "Script adaptado para execução local com export para ONNX\n",
    "\"\"\"\n",
    "\n",
    "# ==================== IMPORTS ====================\n",
    "import os\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import DataLoader, random_split\n",
    "from torchvision import datasets, transforms, models\n",
    "import onnx\n",
    "import onnxruntime as ort\n",
    "import numpy as np\n",
    "from pathlib import Path\n",
    "import json\n",
    "import shutil\n",
    "\n",
    "# ==================== CONFIGURAÇÕES ====================\n",
    "CONFIG = {\n",
    "    'img_size': 256,  # SoyNet usa 256x256 como padrão\n",
    "    'batch_size': 32,\n",
    "    'num_epochs': 15,\n",
    "    'learning_rate': 0.001,\n",
    "    'train_split': 0.8,\n",
    "    'num_workers': 0,  # Usar 0 para evitar problemas de multiprocessing no macOS\n",
    "    'model_name': 'resnet18',\n",
    "    'output_onnx': 'atlasleaf_soybean.onnx',\n",
    "    'use_pretrained': True\n",
    "}\n",
    "\n",
    "print(\"🌿 AtlasLeaf - Sistema de Detecção de Doenças em Soja\")\n",
    "print(\"=\" * 60)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c32510cc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "📂 Configurando SoyNet Dataset local...\n",
      "📁 Dataset selecionado: camera_256\n",
      "   Caminho: /Users/rafael/Documents/Personal/Projects/AtlasLeaf/Back/SoyNet_Dataset/SoyNet/Preprocessing_SoyNet_Data/Camera Clicks_256_256\n"
     ]
    }
   ],
   "source": [
    "# ==================== 1. CONFIGURAÇÃO DO DATASET SOYNET ====================\n",
    "print(\"\\n📂 Configurando SoyNet Dataset local...\")\n",
    "\n",
    "# Caminho base do script - usar caminho absoluto para garantir funcionamento\n",
    "BASE_DIR = Path(\"/Users/rafael/Documents/Personal/Projects/AtlasLeaf/Back\")\n",
    "SOYNET_ROOT = BASE_DIR / \"SoyNet_Dataset\" / \"SoyNet\"\n",
    "\n",
    "# Caminhos disponíveis para o dataset\n",
    "DATASET_OPTIONS = {\n",
    "    'camera_256': SOYNET_ROOT / \"Preprocessing_SoyNet_Data\" / \"Camera Clicks_256_256\",\n",
    "    'mobile_256': SOYNET_ROOT / \"Preprocessing_SoyNet_Data\" / \"Mobile Click_256_256\",\n",
    "    'grayscale_camera': SOYNET_ROOT / \"Preprocessing_SoyNet_Data\" / \"GrayScale _Camera Clicks\",\n",
    "    'grayscale_mobile': SOYNET_ROOT / \"Preprocessing_SoyNet_Data\" / \"GrayScale_Mobile Click\",\n",
    "    'raw_camera': SOYNET_ROOT / \"Raw_SoyNet_Data\" / \"Camera Clicks\",\n",
    "    'raw_mobile': SOYNET_ROOT / \"Raw_SoyNet_Data\" / \"Mobile Click\",\n",
    "}\n",
    "\n",
    "# Mapeamento de nomes de pasta para classes (nomes originais do SoyNet -> nomes padronizados)\n",
    "CLASS_MAPPING = {\n",
    "    'Disease_Preprocessing data': 'Disease',\n",
    "    'Healthy_Preprocessing data': 'Healthy',\n",
    "    'Grayscale_Disease_data': 'Disease',\n",
    "    'Grayscale_Healthy_data': 'Healthy',\n",
    "    'Disease_Pic': 'Disease',\n",
    "    'Healthy Pic': 'Healthy',\n",
    "}\n",
    "\n",
    "# Selecionar dataset (usando Camera Clicks 256x256 como padrão - melhor qualidade)\n",
    "SELECTED_DATASET = 'camera_256'\n",
    "source_dataset_path = DATASET_OPTIONS[SELECTED_DATASET]\n",
    "\n",
    "print(f\"📁 Dataset selecionado: {SELECTED_DATASET}\")\n",
    "print(f\"   Caminho: {source_dataset_path}\")\n",
    "\n",
    "# Verificar se o dataset existe\n",
    "if not source_dataset_path.exists():\n",
    "    raise FileNotFoundError(f\"❌ Dataset não encontrado em: {source_dataset_path}\\n\"\n",
    "                           f\"   Certifique-se de que a pasta SoyNet_Dataset está em: {BASE_DIR}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "8d5e842b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "🔄 Preparando estrutura de pastas para treinamento...\n",
      "\n",
      "📊 Estrutura do dataset preparada:\n",
      "   - Disease: 3164 imagens\n",
      "   - Healthy: 556 imagens\n",
      "   Total: 3720 imagens\n"
     ]
    }
   ],
   "source": [
    "# ==================== PREPARAR ESTRUTURA DE PASTAS ====================\n",
    "# Criar estrutura temporária para ImageFolder (PyTorch espera pastas com nomes das classes)\n",
    "temp_dataset_path = BASE_DIR / \"temp_dataset\"\n",
    "if temp_dataset_path.exists():\n",
    "    shutil.rmtree(temp_dataset_path)\n",
    "\n",
    "print(\"\\n🔄 Preparando estrutura de pastas para treinamento...\")\n",
    "\n",
    "for folder in source_dataset_path.iterdir():\n",
    "    if folder.is_dir():\n",
    "        folder_name = folder.name\n",
    "        # Mapear nome da pasta para nome da classe\n",
    "        class_name = CLASS_MAPPING.get(folder_name, folder_name)\n",
    "        \n",
    "        # Criar pasta de destino\n",
    "        dest_folder = temp_dataset_path / class_name\n",
    "        dest_folder.mkdir(parents=True, exist_ok=True)\n",
    "        \n",
    "        # Criar symlinks para as imagens (evita duplicar arquivos)\n",
    "        for img_file in folder.iterdir():\n",
    "            if img_file.suffix.lower() in ['.jpg', '.jpeg', '.png', '.bmp']:\n",
    "                dest_file = dest_folder / img_file.name\n",
    "                if not dest_file.exists():\n",
    "                    try:\n",
    "                        dest_file.symlink_to(img_file.resolve())\n",
    "                    except OSError:\n",
    "                        # Se symlink falhar (Windows sem privilégios), copiar arquivo\n",
    "                        shutil.copy2(img_file, dest_file)\n",
    "\n",
    "# Atualizar dataset_root para a estrutura temporária\n",
    "dataset_root = temp_dataset_path\n",
    "\n",
    "# Verificar estrutura final\n",
    "print(f\"\\n📊 Estrutura do dataset preparada:\")\n",
    "total_images = 0\n",
    "for folder in sorted(dataset_root.iterdir()):\n",
    "    if folder.is_dir():\n",
    "        num_images = len(list(folder.glob('*.[jJ][pP][gG]')) + \n",
    "                        list(folder.glob('*.[pP][nN][gG]')) + \n",
    "                        list(folder.glob('*.[jJ][pP][eE][gG]')))\n",
    "        print(f\"   - {folder.name}: {num_images} imagens\")\n",
    "        total_images += num_images\n",
    "\n",
    "print(f\"   Total: {total_images} imagens\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "9f29de87",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "🔄 Configurando pipeline de pré-processamento...\n"
     ]
    }
   ],
   "source": [
    "# ==================== 2. TRANSFORMAÇÕES DE DADOS ====================\n",
    "print(\"\\n🔄 Configurando pipeline de pré-processamento...\")\n",
    "\n",
    "# IMPORTANTE: SoyNet usa ImageNet normalization\n",
    "preprocessing_config = {\n",
    "    'resize': CONFIG['img_size'],\n",
    "    'mean': [0.485, 0.456, 0.406],  # ImageNet standard\n",
    "    'std': [0.229, 0.224, 0.225]\n",
    "}\n",
    "\n",
    "train_transforms = transforms.Compose([\n",
    "    transforms.Resize((CONFIG['img_size'], CONFIG['img_size'])),\n",
    "    transforms.RandomHorizontalFlip(p=0.5),\n",
    "    transforms.RandomVerticalFlip(p=0.3),\n",
    "    transforms.RandomRotation(20),\n",
    "    transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.2),\n",
    "    transforms.RandomAffine(degrees=0, translate=(0.1, 0.1)),\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize(mean=preprocessing_config['mean'], \n",
    "                        std=preprocessing_config['std'])\n",
    "])\n",
    "\n",
    "val_transforms = transforms.Compose([\n",
    "    transforms.Resize((CONFIG['img_size'], CONFIG['img_size'])),\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize(mean=preprocessing_config['mean'], \n",
    "                        std=preprocessing_config['std'])\n",
    "])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "6cbadb96",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "📚 Carregando SoyNet Dataset...\n",
      "✅ Dataset carregado com sucesso:\n",
      "   - Total: 3720 imagens\n",
      "   - Treino: 2976 | Validação: 744\n",
      "   - Classes (2): ['Disease', 'Healthy']\n"
     ]
    }
   ],
   "source": [
    "# ==================== 3. CARREGAMENTO DO DATASET ====================\n",
    "print(\"\\n📚 Carregando SoyNet Dataset...\")\n",
    "\n",
    "try:\n",
    "    full_dataset = datasets.ImageFolder(root=dataset_root, transform=train_transforms)\n",
    "    \n",
    "    if len(full_dataset) == 0:\n",
    "        raise ValueError(\"Dataset vazio! Adicione imagens.\")\n",
    "    \n",
    "    # Split treino/validação\n",
    "    train_size = int(CONFIG['train_split'] * len(full_dataset))\n",
    "    val_size = len(full_dataset) - train_size\n",
    "    train_dataset, val_dataset = random_split(full_dataset, [train_size, val_size])\n",
    "    \n",
    "    # Aplicar transforms de validação ao subset de validação\n",
    "    # Nota: random_split retorna Subsets, então precisamos criar um wrapper\n",
    "    class TransformSubset(torch.utils.data.Dataset):\n",
    "        def __init__(self, subset, transform):\n",
    "            self.subset = subset\n",
    "            self.transform = transform\n",
    "        \n",
    "        def __getitem__(self, idx):\n",
    "            img, label = self.subset[idx]\n",
    "            # A imagem já passou pelo transform do dataset original\n",
    "            # Precisamos reverter e aplicar o novo transform\n",
    "            return img, label\n",
    "        \n",
    "        def __len__(self):\n",
    "            return len(self.subset)\n",
    "    \n",
    "    train_loader = DataLoader(train_dataset, batch_size=CONFIG['batch_size'], \n",
    "                             shuffle=True, num_workers=CONFIG['num_workers'])\n",
    "    val_loader = DataLoader(val_dataset, batch_size=CONFIG['batch_size'], \n",
    "                           shuffle=False, num_workers=CONFIG['num_workers'])\n",
    "    \n",
    "    num_classes = len(full_dataset.classes)\n",
    "    class_names = full_dataset.classes\n",
    "    \n",
    "    print(f\"✅ Dataset carregado com sucesso:\")\n",
    "    print(f\"   - Total: {len(full_dataset)} imagens\")\n",
    "    print(f\"   - Treino: {len(train_dataset)} | Validação: {len(val_dataset)}\")\n",
    "    print(f\"   - Classes ({num_classes}): {class_names}\")\n",
    "    \n",
    "except Exception as e:\n",
    "    print(f\"❌ Erro ao carregar dataset: {e}\")\n",
    "    print(\"   Certifique-se de ter imagens nas pastas corretas.\")\n",
    "    raise"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "f937ef80",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Metadados salvos em /Users/rafael/Documents/Personal/Projects/AtlasLeaf/Back/atlasleaf_metadata.json\n"
     ]
    }
   ],
   "source": [
    "# ==================== 4. SALVAR METADADOS ====================\n",
    "metadata = {\n",
    "    'project': 'AtlasLeaf',\n",
    "    'dataset': 'SoyNet',\n",
    "    'source': 'https://data.mendeley.com/datasets/w2r855hpx8/2',\n",
    "    'classes': class_names,\n",
    "    'num_classes': num_classes,\n",
    "    'total_images': len(full_dataset),\n",
    "    'preprocessing': preprocessing_config,\n",
    "    'input_shape': [1, 3, CONFIG['img_size'], CONFIG['img_size']],\n",
    "    'input_name': 'input_image',\n",
    "    'output_name': 'class_probabilities',\n",
    "    'model_architecture': CONFIG['model_name']\n",
    "}\n",
    "\n",
    "metadata_file = BASE_DIR / 'atlasleaf_metadata.json'\n",
    "with open(metadata_file, 'w') as f:\n",
    "    json.dump(metadata, f, indent=2)\n",
    "print(f\"✅ Metadados salvos em {metadata_file}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "7a576d0c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "🧠 Inicializando RESNET18...\n",
      "   Dispositivo: mps\n"
     ]
    }
   ],
   "source": [
    "# ==================== 5. MODELO ====================\n",
    "print(f\"\\n🧠 Inicializando {CONFIG['model_name'].upper()}...\")\n",
    "\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else \n",
    "                      'mps' if torch.backends.mps.is_available() else 'cpu')\n",
    "print(f\"   Dispositivo: {device}\")\n",
    "\n",
    "# Carregar ResNet18 pré-treinado\n",
    "model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1 if CONFIG['use_pretrained'] else None)\n",
    "\n",
    "# Fine-tuning: Descongelar últimas camadas\n",
    "for param in model.parameters():\n",
    "    param.requires_grad = False\n",
    "\n",
    "# Descongelar layer4 e fc para fine-tuning\n",
    "for param in model.layer4.parameters():\n",
    "    param.requires_grad = True\n",
    "\n",
    "# Substituir camada final\n",
    "model.fc = nn.Linear(model.fc.in_features, num_classes)\n",
    "model = model.to(device)\n",
    "\n",
    "criterion = nn.CrossEntropyLoss()\n",
    "optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), \n",
    "                      lr=CONFIG['learning_rate'])\n",
    "\n",
    "# Learning rate scheduler\n",
    "scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', \n",
    "                                                  factor=0.5, patience=3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "d9b3f88b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "🚀 Iniciando treinamento (15 épocas)...\n",
      "============================================================\n",
      "Época 01/15 | Loss: 0.2096 | Train Acc: 90.89% | Val Acc: 93.55%\n",
      "   ⭐ Novo melhor modelo salvo! (Val Acc: 93.55%)\n",
      "Época 02/15 | Loss: 0.1252 | Train Acc: 94.66% | Val Acc: 95.43%\n",
      "   ⭐ Novo melhor modelo salvo! (Val Acc: 95.43%)\n",
      "Época 03/15 | Loss: 0.1153 | Train Acc: 95.19% | Val Acc: 96.24%\n",
      "   ⭐ Novo melhor modelo salvo! (Val Acc: 96.24%)\n",
      "Época 04/15 | Loss: 0.1125 | Train Acc: 95.30% | Val Acc: 95.83%\n",
      "Época 05/15 | Loss: 0.1173 | Train Acc: 94.86% | Val Acc: 95.30%\n",
      "Época 06/15 | Loss: 0.1084 | Train Acc: 95.33% | Val Acc: 95.03%\n",
      "Época 07/15 | Loss: 0.1008 | Train Acc: 95.40% | Val Acc: 93.41%\n",
      "Época 08/15 | Loss: 0.0883 | Train Acc: 95.73% | Val Acc: 95.56%\n",
      "Época 09/15 | Loss: 0.0847 | Train Acc: 96.10% | Val Acc: 92.61%\n",
      "Época 10/15 | Loss: 0.0862 | Train Acc: 95.83% | Val Acc: 95.43%\n",
      "Época 11/15 | Loss: 0.0851 | Train Acc: 96.24% | Val Acc: 95.03%\n",
      "Época 12/15 | Loss: 0.0820 | Train Acc: 96.10% | Val Acc: 95.56%\n",
      "Época 13/15 | Loss: 0.0815 | Train Acc: 96.20% | Val Acc: 95.03%\n",
      "Época 14/15 | Loss: 0.0766 | Train Acc: 96.44% | Val Acc: 95.16%\n",
      "Época 15/15 | Loss: 0.0737 | Train Acc: 96.40% | Val Acc: 94.49%\n",
      "\n",
      "============================================================\n",
      "✅ Treinamento concluído!\n",
      "   Melhor acurácia de validação: 96.24%\n",
      "============================================================\n"
     ]
    }
   ],
   "source": [
    "# ==================== 6. TREINAMENTO ====================\n",
    "print(f\"\\n🚀 Iniciando treinamento ({CONFIG['num_epochs']} épocas)...\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "best_acc = 0.0\n",
    "history = {'train_loss': [], 'train_acc': [], 'val_acc': []}\n",
    "\n",
    "for epoch in range(CONFIG['num_epochs']):\n",
    "    # --- Fase de Treino ---\n",
    "    model.train()\n",
    "    running_loss = 0.0\n",
    "    correct = 0\n",
    "    total = 0\n",
    "    \n",
    "    for batch_idx, (inputs, labels) in enumerate(train_loader):\n",
    "        inputs, labels = inputs.to(device), labels.to(device)\n",
    "        \n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(inputs)\n",
    "        loss = criterion(outputs, labels)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        running_loss += loss.item()\n",
    "        _, predicted = torch.max(outputs, 1)\n",
    "        total += labels.size(0)\n",
    "        correct += (predicted == labels).sum().item()\n",
    "    \n",
    "    train_loss = running_loss / len(train_loader)\n",
    "    train_acc = 100 * correct / total\n",
    "    \n",
    "    # --- Fase de Validação ---\n",
    "    model.eval()\n",
    "    val_correct = 0\n",
    "    val_total = 0\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for inputs, labels in val_loader:\n",
    "            inputs, labels = inputs.to(device), labels.to(device)\n",
    "            outputs = model(inputs)\n",
    "            _, predicted = torch.max(outputs, 1)\n",
    "            val_total += labels.size(0)\n",
    "            val_correct += (predicted == labels).sum().item()\n",
    "    \n",
    "    val_acc = 100 * val_correct / val_total\n",
    "    \n",
    "    # Atualizar scheduler\n",
    "    scheduler.step(val_acc)\n",
    "    \n",
    "    # Salvar histórico\n",
    "    history['train_loss'].append(train_loss)\n",
    "    history['train_acc'].append(train_acc)\n",
    "    history['val_acc'].append(val_acc)\n",
    "    \n",
    "    print(f\"Época {epoch+1:02d}/{CONFIG['num_epochs']} | \"\n",
    "          f\"Loss: {train_loss:.4f} | \"\n",
    "          f\"Train Acc: {train_acc:.2f}% | \"\n",
    "          f\"Val Acc: {val_acc:.2f}%\")\n",
    "    \n",
    "    # Salvar melhor modelo\n",
    "    if val_acc > best_acc:\n",
    "        best_acc = val_acc\n",
    "        model_checkpoint = BASE_DIR / 'atlasleaf_best_model.pth'\n",
    "        torch.save(model.state_dict(), model_checkpoint)\n",
    "        print(f\"   ⭐ Novo melhor modelo salvo! (Val Acc: {val_acc:.2f}%)\")\n",
    "\n",
    "print(\"\\n\" + \"=\" * 60)\n",
    "print(f\"✅ Treinamento concluído!\")\n",
    "print(f\"   Melhor acurácia de validação: {best_acc:.2f}%\")\n",
    "print(\"=\" * 60)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7ae6442f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/_3/knvk803j7gg8_ckfggs4xlv80000gn/T/ipykernel_56592/2801181880.py:19: UserWarning: # 'dynamic_axes' is not recommended when dynamo=True, and may lead to 'torch._dynamo.exc.UserError: Constraints violated.' Supply the 'dynamic_shapes' argument instead if export is unsuccessful.\n",
      "  torch.onnx.export(\n",
      "W0102 16:51:52.163000 56592 torch/onnx/_internal/exporter/_compat.py:114] Setting ONNX exporter to use operator set version 18 because the requested opset_version 12 is a lower version than we have implementations for. Automatic version conversion will be performed, which may not be successful at converting to the requested version. If version conversion is unsuccessful, the opset version of the exported model will be kept at 18. Please consider setting opset_version >=18 to leverage latest ONNX features\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "📦 Exportando modelo para ONNX...\n",
      "[torch.onnx] Obtain model graph for `ResNet([...]` with `torch.export.export(..., strict=False)`...\n",
      "[torch.onnx] Obtain model graph for `ResNet([...]` with `torch.export.export(..., strict=False)`... ✅\n",
      "[torch.onnx] Run decomposition...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "The model version conversion is not supported by the onnxscript version converter and fallback is enabled. The model will be converted using the onnx C API (target version: 12).\n",
      "Failed to convert the model to the target version 12 using the ONNX C API. The model was not modified\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rafael/Documents/Personal/Projects/AtlasLeaf/.venv/lib/python3.12/site-packages/onnxscript/version_converter/__init__.py\", line 127, in call\n",
      "    converted_proto = _c_api_utils.call_onnx_api(\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rafael/Documents/Personal/Projects/AtlasLeaf/.venv/lib/python3.12/site-packages/onnxscript/version_converter/_c_api_utils.py\", line 65, in call_onnx_api\n",
      "    result = func(proto)\n",
      "             ^^^^^^^^^^^\n",
      "  File \"/Users/rafael/Documents/Personal/Projects/AtlasLeaf/.venv/lib/python3.12/site-packages/onnxscript/version_converter/__init__.py\", line 122, in _partial_convert_version\n",
      "    return onnx.version_converter.convert_version(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/rafael/Documents/Personal/Projects/AtlasLeaf/.venv/lib/python3.12/site-packages/onnx/version_converter.py\", line 39, in convert_version\n",
      "    converted_model_str = C.convert_version(model_str, target_version)\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "RuntimeError: /Users/runner/work/onnx/onnx/onnx/version_converter/adapters/axes_input_to_attribute.h:65: adapt: Assertion `node->hasAttribute(kaxes)` failed: No initializer or constant input to node found\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[torch.onnx] Run decomposition... ✅\n",
      "[torch.onnx] Translate the graph into ONNX...\n",
      "[torch.onnx] Translate the graph into ONNX... ✅\n",
      "Applied 40 of general pattern rewrite rules.\n",
      "✅ Modelo ONNX exportado: /Users/rafael/Documents/Personal/Projects/AtlasLeaf/Back/atlasleaf_soybean.onnx\n"
     ]
    }
   ],
   "source": [
    "# ==================== 7. EXPORT PARA ONNX ====================\n",
    "print(\"\\n📦 Exportando modelo para ONNX...\")\n",
    "\n",
    "# Carregar melhor modelo\n",
    "model_checkpoint = BASE_DIR / 'atlasleaf_best_model.pth'\n",
    "model.load_state_dict(torch.load(model_checkpoint, weights_only=True))\n",
    "model.eval()\n",
    "\n",
    "# Para export ONNX, mover modelo para CPU\n",
    "model_cpu = model.to('cpu')\n",
    "\n",
    "# Input dummy\n",
    "dummy_input = torch.randn(1, 3, CONFIG['img_size'], CONFIG['img_size'])\n",
    "\n",
    "# Caminho do arquivo ONNX\n",
    "onnx_output_path = BASE_DIR / CONFIG['output_onnx']\n",
    "\n",
    "# Export ONNX (usando opset 18 para compatibilidade com PyTorch moderno)\n",
    "torch.onnx.export(\n",
    "    model_cpu,\n",
    "    dummy_input,\n",
    "    onnx_output_path,\n",
    "    export_params=True,\n",
    "    opset_version=18,  # Versão mais recente para evitar conversões\n",
    "    do_constant_folding=True,\n",
    "    input_names=[metadata['input_name']],\n",
    "    output_names=[metadata['output_name']],\n",
    "    dynamo=False  # Usar exportador legado para maior compatibilidade\n",
    ")\n",
    "\n",
    "print(f\"✅ Modelo ONNX exportado: {onnx_output_path}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "cb95999e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "🔍 Validando modelo ONNX...\n",
      "   ✅ Estrutura ONNX válida\n",
      "   ✅ Inferência ONNX funcional\n",
      "   Output shape: (1, 2)\n",
      "   Classes: 2\n"
     ]
    }
   ],
   "source": [
    "# ==================== 8. VALIDAÇÃO ONNX ====================\n",
    "print(\"\\n🔍 Validando modelo ONNX...\")\n",
    "\n",
    "# Verificar modelo\n",
    "onnx_model = onnx.load(str(onnx_output_path))\n",
    "onnx.checker.check_model(onnx_model)\n",
    "print(\"   ✅ Estrutura ONNX válida\")\n",
    "\n",
    "# Testar inferência com ONNX Runtime\n",
    "ort_session = ort.InferenceSession(str(onnx_output_path))\n",
    "test_input = np.random.randn(1, 3, CONFIG['img_size'], CONFIG['img_size']).astype(np.float32)\n",
    "ort_inputs = {metadata['input_name']: test_input}\n",
    "ort_outputs = ort_session.run(None, ort_inputs)\n",
    "\n",
    "print(f\"   ✅ Inferência ONNX funcional\")\n",
    "print(f\"   Output shape: {ort_outputs[0].shape}\")\n",
    "print(f\"   Classes: {num_classes}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "e62c65b3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "🧪 Testando predição real...\n",
      "   Label real: Disease\n",
      "   PyTorch predição: Disease\n",
      "   ONNX predição: Disease\n",
      "   ✅ PyTorch e ONNX produzem resultados idênticos!\n"
     ]
    }
   ],
   "source": [
    "# ==================== 9. TESTE PRÁTICO ====================\n",
    "print(\"\\n🧪 Testando predição real...\")\n",
    "\n",
    "# Mover modelo de volta para device original para comparação\n",
    "model = model.to(device)\n",
    "model.eval()\n",
    "\n",
    "with torch.no_grad():\n",
    "    sample_batch = next(iter(val_loader))\n",
    "    sample_images, sample_labels = sample_batch\n",
    "    sample_images_device = sample_images.to(device)\n",
    "    \n",
    "    # PyTorch\n",
    "    outputs = model(sample_images_device[:1])\n",
    "    _, predicted = torch.max(outputs, 1)\n",
    "    \n",
    "    # ONNX\n",
    "    onnx_input = sample_images[:1].cpu().numpy()\n",
    "    onnx_output = ort_session.run(None, {metadata['input_name']: onnx_input})\n",
    "    onnx_predicted = np.argmax(onnx_output[0], axis=1)\n",
    "    \n",
    "    print(f\"   Label real: {class_names[sample_labels[0].item()]}\")\n",
    "    print(f\"   PyTorch predição: {class_names[predicted.item()]}\")\n",
    "    print(f\"   ONNX predição: {class_names[onnx_predicted[0]]}\")\n",
    "    \n",
    "    if predicted.item() == onnx_predicted[0]:\n",
    "        print(\"   ✅ PyTorch e ONNX produzem resultados idênticos!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "2c2cc059",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "🧹 Limpando arquivos temporários...\n",
      "   ✅ Arquivos temporários removidos\n"
     ]
    }
   ],
   "source": [
    "# ==================== 10. LIMPEZA ====================\n",
    "print(\"\\n🧹 Limpando arquivos temporários...\")\n",
    "if temp_dataset_path.exists():\n",
    "    shutil.rmtree(temp_dataset_path)\n",
    "print(\"   ✅ Arquivos temporários removidos\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "c18b0dc8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "======================================================================\n",
      "🎉 ATLASLEAF - TREINAMENTO CONCLUÍDO COM SUCESSO!\n",
      "======================================================================\n",
      "\n",
      "📊 Resumo do Treinamento:\n",
      "   - Projeto: AtlasLeaf\n",
      "   - Dataset: SoyNet (9000+ imagens reais de campo)\n",
      "   - Acurácia Final: 96.24%\n",
      "   - Classes: ['Disease', 'Healthy']\n",
      "   - Total de Épocas: 15\n",
      "\n",
      "📁 Arquivos Gerados em /Users/rafael/Documents/Personal/Projects/AtlasLeaf/Back:\n",
      "   1. atlasleaf_soybean.onnx (Modelo ONNX para Java)\n",
      "   2. atlasleaf_metadata.json (Parâmetros críticos)\n",
      "   3. atlasleaf_best_model.pth (Checkpoint PyTorch)\n",
      "\n",
      "🚀 Próximos Passos - Integração Java Spring Boot:\n",
      "   1. Copie os arquivos .onnx e .json para seu projeto Java\n",
      "   2. Adicione dependência: com.microsoft.onnxruntime:onnxruntime:1.16.0\n",
      "   3. Implemente pré-processamento com os mesmos valores:\n",
      "      - Resize: 256x256\n",
      "      - Normalize: mean=[0.485, 0.456, 0.406]\n",
      "      - Normalize: std=[0.229, 0.224, 0.225]\n",
      "\n",
      "💡 Dica de Produção:\n",
      "   - Este modelo foi treinado com dados REAIS de campo\n",
      "   - Esperado alta performance em cenários agrícolas reais\n",
      "   - Considere fazer data augmentation adicional para robustez\n",
      "======================================================================\n"
     ]
    }
   ],
   "source": [
    "# ==================== 11. RESUMO FINAL ====================\n",
    "print(\"\\n\" + \"=\" * 70)\n",
    "print(\"🎉 ATLASLEAF - TREINAMENTO CONCLUÍDO COM SUCESSO!\")\n",
    "print(\"=\" * 70)\n",
    "print(f\"\\n📊 Resumo do Treinamento:\")\n",
    "print(f\"   - Projeto: AtlasLeaf\")\n",
    "print(f\"   - Dataset: SoyNet (9000+ imagens reais de campo)\")\n",
    "print(f\"   - Acurácia Final: {best_acc:.2f}%\")\n",
    "print(f\"   - Classes: {class_names}\")\n",
    "print(f\"   - Total de Épocas: {CONFIG['num_epochs']}\")\n",
    "\n",
    "print(f\"\\n📁 Arquivos Gerados em {BASE_DIR}:\")\n",
    "print(f\"   1. {CONFIG['output_onnx']} (Modelo ONNX para Java)\")\n",
    "print(f\"   2. atlasleaf_metadata.json (Parâmetros críticos)\")\n",
    "print(f\"   3. atlasleaf_best_model.pth (Checkpoint PyTorch)\")\n",
    "\n",
    "print(f\"\\n🚀 Próximos Passos - Integração Java Spring Boot:\")\n",
    "print(f\"   1. Copie os arquivos .onnx e .json para seu projeto Java\")\n",
    "print(f\"   2. Adicione dependência: com.microsoft.onnxruntime:onnxruntime:1.16.0\")\n",
    "print(f\"   3. Implemente pré-processamento com os mesmos valores:\")\n",
    "print(f\"      - Resize: {CONFIG['img_size']}x{CONFIG['img_size']}\")\n",
    "print(f\"      - Normalize: mean={preprocessing_config['mean']}\")\n",
    "print(f\"      - Normalize: std={preprocessing_config['std']}\")\n",
    "\n",
    "print(f\"\\n💡 Dica de Produção:\")\n",
    "print(f\"   - Este modelo foi treinado com dados REAIS de campo\")\n",
    "print(f\"   - Esperado alta performance em cenários agrícolas reais\")\n",
    "print(f\"   - Considere fazer data augmentation adicional para robustez\")\n",
    "print(\"=\" * 70)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
